version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    S3_BUCKET: "crypto-app-artifacts1"  # Your S3 Bucket Name
    BUILD_FOLDER: "crypto-app-build"   # Folder inside S3 where imageDetail.json is stored

phases:
  pre_build:
    commands:
      - echo "Fetching imageDetail.json from S3 artifacts..."
      - aws s3 cp s3://$S3_BUCKET/$BUILD_FOLDER/imageDetail.json .

      - echo "Extracting IMAGE_URI from imageDetail.json..."
      - IMAGE_URI=$(jq -r '.imageURI' imageDetail.json)
      - |
       echo "Using Image URI: $IMAGE_URI"

      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $IMAGE_URI | cut -d'/' -f1)
      - echo "ECR login successful."

  build:
    commands:
      - echo "Re-extracting IMAGE_URI..."
      - IMAGE_URI=$(jq -r '.imageURI' imageDetail.json)  # Extract again

      - echo "Pulling the Docker image from Amazon ECR..."
      - docker pull $IMAGE_URI
      - echo "Docker image pulled successfully."

      # Start container and run tests
      - echo "Running tests inside Docker container..."
      - CONTAINER_ID=$(docker run -d -p 5000:5000 $IMAGE_URI)
      - |
       echo "Running container ID: $CONTAINER_ID"

      # Wait for the service to start
      - echo "Waiting for the container to be ready..."
      - sleep 10  # Increased sleep time for stability

      # Get Docker container IP address
      - CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID)
      - |
       echo "Container is running at: http://$CONTAINER_IP:5000"

      # Run API health check
      - echo "Checking service health..."
      - curl -sSf http://$CONTAINER_IP:5000/ || (echo "Health check failed!" && exit 1)

  post_build:
    commands:
      - echo "Stopping and removing container..."
      - docker stop $CONTAINER_ID
      - docker rm $CONTAINER_ID
      - echo "Test job completed successfully."
