version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    S3_BUCKET: "crypto-app-artifacts1"
    BUILD_FOLDER: "crypto-app-build"

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - yum install -y jq

      - echo "Fetching imageDetail.json from S3..."
      - aws s3 cp s3://$S3_BUCKET/$BUILD_FOLDER/imageDetail.json .

      - echo "Extracting IMAGE_URI..."
      - export IMAGE_URI=$(jq -r '.imageURI' imageDetail.json)
      - echo "Using Image URI: $IMAGE_URI"

      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $(echo $IMAGE_URI | cut -d'/' -f1)
      - echo "ECR login successful."

  build:
    commands:
      - echo "Pulling the Docker image from ECR..."
      - docker pull $IMAGE_URI

      - echo "Starting container from image with port mapping..."
      - docker run -d -p 5000:5000 --name test_container $IMAGE_URI

      - echo "Waiting for the container to be ready..."
      - sleep 10

      - echo "Running health check on localhost:5000..."
      - |
        set +e
        curl -sSf http://localhost:5000/
        TEST_EXIT_CODE=$?
        docker stop test_container
        docker rm test_container
        exit $TEST_EXIT_CODE

  post_build:
    commands:
      - echo "Test stage completed."
